### PR TITLE
Enable cross platform support

### PR DESCRIPTION
**Pull request by JoeEcob**
Converts the project from a PCL to .Net Standard 1.1. .Net Standard supports a wider range of platforms whilst still being backwards compatible, this means it can now be used with .Net core on Linux.

We're targetting 1.1 with these changes to maintain existing platform targets, see:
https://docs.microsoft.com/en-gb/dotnet/standard/net-standard

.Net Standard also massively simplifies the .csproj file - it now contains all the information about the project, including nuget configuration.

### CODE REVIEW

**Comment by rdingwall** [comment]
Thanks @JoeEcob this is really great! I'll review and merge in the next couple of days 👍

**Comment by rdingwall** [comment]
@JoeEcob appveyor is having some trouble building your PR. Can you please try adding the following to `appveyor.yml`?

```
image: Visual Studio 2017
```

**Comment by JoeEcob** [comment]
@rdingwall All sorted, thanks. Appveyor should now be doing the same versioning etc. as before 👍

**Comment by rdingwall** [comment]
@JoeEcob many thanks! 🙌

**Pull request merged**
